[project]
name = "authorize-apparatus"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.access-control]
path = "contracts/access-control.clar"
depends_on = []

[contracts.transaction-handler]
path = "contracts/transaction-handler.clar"
depends_on = []

[contracts.trust-manager]
path = "contracts/trust-manager.clar"
depends_on = []

[contracts.activity-monitor]
path = "contracts/activity-monitor.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
